export const MOCK_DATA = {
  cards: [
    {
      id: "1",
      isDefault: true,
      balance: 5756,
      cardHolder: "Eddy Cusuma",
      validThru: "12/22",
      cardNumber: "3778 **** **** 1234",
    },
    {
      id: "2",
      isDefault: false,
      balance: 8432.19,
      cardHolder: "Sarah Johnson",
      validThru: "08/26",
      cardNumber: "4532 **** **** 5678",
    },
  ],
  transactions: [
    {
      id: "1",
      type: "card" as const,
      title: "Deposit from my Card",
      date: "28 January 2021",
      amount: 850,
      flow: "debit" as const,
    },
    {
      id: "2",
      type: "paypal" as const,
      title: "Deposit Paypal",
      date: "25 January 2021",
      amount: 2500,
      flow: "credit" as const,
    },
    {
      id: "3",
      type: "cash" as const,
      title: "Jemi Wilson",
      date: "21 January 2021",
      amount: 5450,
      flow: "credit" as const,
    },
  ],
  weeklyActivity: [
    { day: "Sat", deposit: 220, withdraw: 480 },
    { day: "Sun", deposit: 130, withdraw: 350 },
    { day: "Mon", deposit: 275, withdraw: 330 },
    { day: "Tue", deposit: 380, withdraw: 490 },
    { day: "Wed", deposit: 230, withdraw: 155 },
    { day: "Thu", deposit: 230, withdraw: 390 },
    { day: "Fri", deposit: 330, withdraw: 390 },
  ],
  expenseStats: [
    {
      name: "Bill Expense",
      percentage: 15,
      amount: 1500,
      color: "#FC7900",
    },
    {
      name: "Entertainment",
      percentage: 30,
      amount: 3000,
      color: "#343C6A",
    },
    {
      name: "Investment",
      percentage: 35,
      amount: 3500,
      color: "#396AFF",
    },
    {
      name: "Others",
      percentage: 20,
      amount: 2000,
      color: "#232323",
    },
  ],
  balanceHistory: [
    { month: "Jun", value: 160 },
    { month: "Jul", value: 640 },
    { month: "Aug", value: 440 },
    { month: "Sep", value: 250 },
    { month: "Oct", value: 1000 },
    { month: "Nov", value: 400 },
    { month: "Dec", value: 700 },
    { month: "Jan", value: 220 },
  ],
  contacts: [
    {
      id: "1",
      name: "Livia Bator",
      role: "CEO",
      image: "/images/livia.png",
    },
    {
      id: "2",
      name: "Randy Press",
      role: "Director",
      image: "/images/randy.png",
    },
    {
      id: "3",
      name: "Workman",
      role: "Designer",
      image: "/images/workman.png",
    },
  ],
  userProfile: {
    yourName: "Charlene Reed",
    userName: "charlenereed",
    email: "charlenereed@gmail.com",
    dateOfBirth: "",
    presentAddress: "",
    permanentAddress: "",
    postalCode: "",
    city: "",
    country: "",
    profileImage: "/images/profile-picture.png",
  },
};
